{"name": "Проверка ошибки при принятии заказа с неверным id заказа", "status": "passed", "steps": [{"name": "Попытка принять заказ с несуществующим id заказа", "status": "passed", "start": 1760866196524, "stop": 1760866196910}], "start": 1760866196524, "stop": 1760866196912, "uuid": "1950002d-0c35-4662-8804-22d516b2e72b", "historyId": "b40e7e2ec867c89dd1c78f4c9453cf34", "testCaseId": "b40e7e2ec867c89dd1c78f4c9453cf34", "fullName": "tests.tests_orders.test_order_accept.TestOrderAccept#test_order_accept_error_with_wrong_order_id", "labels": [{"name": "parentSuite", "value": "tests.tests_orders"}, {"name": "suite", "value": "test_order_accept"}, {"name": "subSuite", "value": "TestOrderAccept"}, {"name": "host", "value": "Sergei"}, {"name": "thread", "value": "9908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_orders.test_order_accept"}], "titlePath": ["tests", "tests_orders", "test_order_accept.py", "TestOrderAccept"]}