{"name": "Проверка получения ошибки при повторном использовании логина для создания курьера", "status": "passed", "description": "Проверяются код и тело ответа.", "steps": [{"name": "Попытка создания второго курьера с тем же логином", "status": "passed", "start": 1760865206882, "stop": 1760865207637}], "start": 1760865206882, "stop": 1760865207638, "uuid": "1ec96462-2fb8-44ae-b3ee-5efb049a82f0", "historyId": "fa8dadfcce5ef2dd1fdd6c75ddb29064", "testCaseId": "fa8dadfcce5ef2dd1fdd6c75ddb29064", "fullName": "tests.tests_couriers.test_courier_create.TestCourierCreate#test_create_courier_account_login_conflict", "labels": [{"name": "parentSuite", "value": "tests.tests_couriers"}, {"name": "suite", "value": "test_courier_create"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "Sergei"}, {"name": "thread", "value": "5332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_couriers.test_courier_create"}], "titlePath": ["tests", "tests_couriers", "test_courier_create.py", "TestCourierCreate"]}