{"name": "Проверка ошибки при принятии заказа с неверным id курьера", "status": "passed", "steps": [{"name": "Попытка принять заказ с несуществующим id курьера", "status": "passed", "start": 1760866193985, "stop": 1760866194463}], "start": 1760866193985, "stop": 1760866194464, "uuid": "633b73db-3a8c-4af8-80fc-7e1ae1ad4449", "historyId": "da2674241508bc942b000d423694d82d", "testCaseId": "da2674241508bc942b000d423694d82d", "fullName": "tests.tests_orders.test_order_accept.TestOrderAccept#test_order_accept_error_with_wrong_courier_id", "labels": [{"name": "parentSuite", "value": "tests.tests_orders"}, {"name": "suite", "value": "test_order_accept"}, {"name": "subSuite", "value": "TestOrderAccept"}, {"name": "host", "value": "Sergei"}, {"name": "thread", "value": "9908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_orders.test_order_accept"}], "titlePath": ["tests", "tests_orders", "test_order_accept.py", "TestOrderAccept"]}