{"name": "Проверка ошибки при получении заказа без номера", "status": "passed", "steps": [{"name": "Попытка получить заказ без указания track номера", "status": "passed", "start": 1760865226610, "stop": 1760865227038}], "start": 1760865226610, "stop": 1760865227039, "uuid": "589bfb55-0ad4-41b2-b5a2-77491ffd2d16", "historyId": "e4f5f0f6d841da2c29921b6a81ef48c4", "testCaseId": "e4f5f0f6d841da2c29921b6a81ef48c4", "fullName": "tests.tests_orders.test_order_get_by_track.TestOrderGetByTrack#test_order_get_by_track_error_without_track", "labels": [{"name": "parentSuite", "value": "tests.tests_orders"}, {"name": "suite", "value": "test_order_get_by_track"}, {"name": "subSuite", "value": "TestOrderGetByTrack"}, {"name": "host", "value": "Sergei"}, {"name": "thread", "value": "5332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_orders.test_order_get_by_track"}], "titlePath": ["tests", "tests_orders", "test_order_get_by_track.py", "TestOrderGetByTrack"]}